## 신경망을 행렬 곱으로 구현 

In [3]:
import numpy as np 

In [5]:
X = np.array( [1, 2])  
X.shape               # 1-D 배열 (=벡터)
                      # 1 x 2 입력 벡터 

(2,)

In [10]:
W = np.array([ [1, 3, 5],
                [2, 4, 6]]) 
print(W)     
W.shape        # 2-D 배열(=행렬)
               # 2 x 3 가중치 행렬 

[[1 3 5]
 [2 4 6]]


(2, 3)

In [11]:
Y = np.dot(X, W)
print(Y)

[ 5 11 17]
