## softmax function 구현 

In [5]:
import numpy as np 

In [6]:
a         = np.array( [0.3, 2.9, 4.0 ])  #axon 입력 신호 
print(a)

[0.3 2.9 4. ]


In [7]:
exp_a     = np.exp(a)                   #지수 함수 
print(exp_a)

[ 1.34985881 18.17414537 54.59815003]


In [8]:
sum_exp_a  = np.sum(exp_a)               #분모_지수 함수의 합 
print(sum_exp_a)

74.1221542101633


In [9]:
y          = exp_a / sum_exp_a 
print(y)

[0.01821127 0.24519181 0.73659691]


## softmax function을 함수로 정의 

In [10]:
def softmax(a):
    exp_a     = np.exp(a)     #지수 함수 
    sum_exp_a = np.sum(exp_a) #분모_지수 합수의 합
    y         = exp_a / sum_exp_a 
    
    return y 

In [11]:
y     = softmax(a)
print(y)

[0.01821127 0.24519181 0.73659691]


## exp()와 오버플로우 문제 

In [25]:
a    = np.array( [1010, 1000, 990])   #axon 입력 
print(a)

[1010 1000  990]


In [27]:
np.sum(np.exp(a))

inf

In [29]:
np.exp(a)

array([inf, inf, inf])

In [30]:
y    =    np.exp(a) / np.sum(np.exp(a))    # softmax function 계산 
                                           # 하지만 
                                           # [무한대, 무한대, 무한대] / 무한대  

C:\Users\Guhnoo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [31]:
print(y)                                     #[nan nan nan] not a number로 
                                             # 계산 불능 상태                                              

[nan nan nan]


## 개선된 softmax function을 사용

In [16]:
c    =  np.max(a)         # c = 1010 (최대값)
print(c)

1010


In [20]:
a  -  c                   # 브로드캐스팅 연산 
print(a - c)              # 입력 신호를 최대값으로 빼줌 

[  0 -10 -20]


In [22]:
y    =    np.exp(a - c) / np.sum(np.exp(a - c))
print(y)                  # 오버플로에 대한 대책이 마련됨 

[9.99954600e-01 4.53978686e-05 2.06106005e-09]


## 개선된 softmax function 정의 

In [23]:
def modified_softmax(a):
    c         =  np.max(a)     # 최대값 반환 
    exp_a     =  np.exp(a - c) # 오버플로 대책 
    sum_exp_a =  np.sum(exp_a)
    y         = exp_a / sum_exp_a
    
    return y 

In [24]:
y    =  modified_softmax(a)
print(y)

[9.99954600e-01 4.53978686e-05 2.06106005e-09]
