# 활성화 함수 계층 구현하기 

computational graph를 신경망에 적용한다. <br/>
* 신경망을 구성하는 계층(layer) 각각을 클래스 하나로 구현한다. 

In [7]:
# coding: utf-8
import numpy as np
import sys, os 
sys.path.append( os.pardir )  # to import modules from 'common' directory
                              # (Book page. 97)

In [8]:
from common.functions import *
from common.util import im2col, col2im

## ReLU 계층 

p.165

![](./images/fig_5-18.png)

In [10]:
class Relu: 
    def __init__(self):
        self.mask = None 
        
    def forward(self, x_in):
        self.mask = (x_in <= 0)  
        out = x_in.copy()
        out[self.mask] = 0 
        
        return out 
    
    def backward(self, dout):
        dout[self.mask] = 0 
        dx = dout 
        
        return dx 

## mask 기법 

![](./images/fig_mask.jpg)

In [20]:
x = np.array( [[1.0, 2.0], [3.0, 4.0],[5.0, 6.0]])
print(x)
print(x.shape)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
(3, 2)


In [21]:
mask = ( x > 2)
print(mask)

[[False False]
 [ True  True]
 [ True  True]]


In [22]:
out = x.copy()
print(out)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [23]:
print( out[mask] )

[3. 4. 5. 6.]
